// Generated by gencpp from file icra_roboin_msgs/PitchGain.msg
// DO NOT EDIT!


#ifndef ICRA_ROBOIN_MSGS_MESSAGE_PITCHGAIN_H
#define ICRA_ROBOIN_MSGS_MESSAGE_PITCHGAIN_H

#include <ros/service_traits.h>


#include <icra_roboin_msgs/PitchGainRequest.h>
#include <icra_roboin_msgs/PitchGainResponse.h>


namespace icra_roboin_msgs
{

struct PitchGain
{

typedef PitchGainRequest Request;
typedef PitchGainResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct PitchGain
} // namespace icra_roboin_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::icra_roboin_msgs::PitchGain > {
  static const char* value()
  {
    return "223542de9427e9df0f0b5bfbdc1715cb";
  }

  static const char* value(const ::icra_roboin_msgs::PitchGain&) { return value(); }
};

template<>
struct DataType< ::icra_roboin_msgs::PitchGain > {
  static const char* value()
  {
    return "icra_roboin_msgs/PitchGain";
  }

  static const char* value(const ::icra_roboin_msgs::PitchGain&) { return value(); }
};


// service_traits::MD5Sum< ::icra_roboin_msgs::PitchGainRequest> should match 
// service_traits::MD5Sum< ::icra_roboin_msgs::PitchGain > 
template<>
struct MD5Sum< ::icra_roboin_msgs::PitchGainRequest>
{
  static const char* value()
  {
    return MD5Sum< ::icra_roboin_msgs::PitchGain >::value();
  }
  static const char* value(const ::icra_roboin_msgs::PitchGainRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::icra_roboin_msgs::PitchGainRequest> should match 
// service_traits::DataType< ::icra_roboin_msgs::PitchGain > 
template<>
struct DataType< ::icra_roboin_msgs::PitchGainRequest>
{
  static const char* value()
  {
    return DataType< ::icra_roboin_msgs::PitchGain >::value();
  }
  static const char* value(const ::icra_roboin_msgs::PitchGainRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::icra_roboin_msgs::PitchGainResponse> should match 
// service_traits::MD5Sum< ::icra_roboin_msgs::PitchGain > 
template<>
struct MD5Sum< ::icra_roboin_msgs::PitchGainResponse>
{
  static const char* value()
  {
    return MD5Sum< ::icra_roboin_msgs::PitchGain >::value();
  }
  static const char* value(const ::icra_roboin_msgs::PitchGainResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::icra_roboin_msgs::PitchGainResponse> should match 
// service_traits::DataType< ::icra_roboin_msgs::PitchGain > 
template<>
struct DataType< ::icra_roboin_msgs::PitchGainResponse>
{
  static const char* value()
  {
    return DataType< ::icra_roboin_msgs::PitchGain >::value();
  }
  static const char* value(const ::icra_roboin_msgs::PitchGainResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ICRA_ROBOIN_MSGS_MESSAGE_PITCHGAIN_H
