// Generated by gencpp from file icra_roboin_msgs/XYOffsetRequest.msg
// DO NOT EDIT!


#ifndef ICRA_ROBOIN_MSGS_MESSAGE_XYOFFSETREQUEST_H
#define ICRA_ROBOIN_MSGS_MESSAGE_XYOFFSETREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace icra_roboin_msgs
{
template <class ContainerAllocator>
struct XYOffsetRequest_
{
  typedef XYOffsetRequest_<ContainerAllocator> Type;

  XYOffsetRequest_()
    : x_offset(0)
    , y_offset(0)  {
    }
  XYOffsetRequest_(const ContainerAllocator& _alloc)
    : x_offset(0)
    , y_offset(0)  {
  (void)_alloc;
    }



   typedef int8_t _x_offset_type;
  _x_offset_type x_offset;

   typedef int8_t _y_offset_type;
  _y_offset_type y_offset;





  typedef boost::shared_ptr< ::icra_roboin_msgs::XYOffsetRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::icra_roboin_msgs::XYOffsetRequest_<ContainerAllocator> const> ConstPtr;

}; // struct XYOffsetRequest_

typedef ::icra_roboin_msgs::XYOffsetRequest_<std::allocator<void> > XYOffsetRequest;

typedef boost::shared_ptr< ::icra_roboin_msgs::XYOffsetRequest > XYOffsetRequestPtr;
typedef boost::shared_ptr< ::icra_roboin_msgs::XYOffsetRequest const> XYOffsetRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::icra_roboin_msgs::XYOffsetRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::icra_roboin_msgs::XYOffsetRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace icra_roboin_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'icra_roboin_msgs': ['/home/nvidia/Desktop/tae_han_test_final/src/icra_roboin_msgs/msg', '/home/nvidia/Desktop/tae_han_test_final/devel/share/icra_roboin_msgs/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'nav_msgs': ['/opt/ros/kinetic/share/nav_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::icra_roboin_msgs::XYOffsetRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::icra_roboin_msgs::XYOffsetRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::icra_roboin_msgs::XYOffsetRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::icra_roboin_msgs::XYOffsetRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::icra_roboin_msgs::XYOffsetRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::icra_roboin_msgs::XYOffsetRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::icra_roboin_msgs::XYOffsetRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "52d0410d68abc4c057c9602bab186b90";
  }

  static const char* value(const ::icra_roboin_msgs::XYOffsetRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x52d0410d68abc4c0ULL;
  static const uint64_t static_value2 = 0x57c9602bab186b90ULL;
};

template<class ContainerAllocator>
struct DataType< ::icra_roboin_msgs::XYOffsetRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "icra_roboin_msgs/XYOffsetRequest";
  }

  static const char* value(const ::icra_roboin_msgs::XYOffsetRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::icra_roboin_msgs::XYOffsetRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int8 x_offset\n\
int8 y_offset\n\
";
  }

  static const char* value(const ::icra_roboin_msgs::XYOffsetRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::icra_roboin_msgs::XYOffsetRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x_offset);
      stream.next(m.y_offset);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct XYOffsetRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::icra_roboin_msgs::XYOffsetRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::icra_roboin_msgs::XYOffsetRequest_<ContainerAllocator>& v)
  {
    s << indent << "x_offset: ";
    Printer<int8_t>::stream(s, indent + "  ", v.x_offset);
    s << indent << "y_offset: ";
    Printer<int8_t>::stream(s, indent + "  ", v.y_offset);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ICRA_ROBOIN_MSGS_MESSAGE_XYOFFSETREQUEST_H
