// Generated by gencpp from file icra_roboin_msgs/XYOffset.msg
// DO NOT EDIT!


#ifndef ICRA_ROBOIN_MSGS_MESSAGE_XYOFFSET_H
#define ICRA_ROBOIN_MSGS_MESSAGE_XYOFFSET_H

#include <ros/service_traits.h>


#include <icra_roboin_msgs/XYOffsetRequest.h>
#include <icra_roboin_msgs/XYOffsetResponse.h>


namespace icra_roboin_msgs
{

struct XYOffset
{

typedef XYOffsetRequest Request;
typedef XYOffsetResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct XYOffset
} // namespace icra_roboin_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::icra_roboin_msgs::XYOffset > {
  static const char* value()
  {
    return "d8dc129d6dde9852a52847783f565dfc";
  }

  static const char* value(const ::icra_roboin_msgs::XYOffset&) { return value(); }
};

template<>
struct DataType< ::icra_roboin_msgs::XYOffset > {
  static const char* value()
  {
    return "icra_roboin_msgs/XYOffset";
  }

  static const char* value(const ::icra_roboin_msgs::XYOffset&) { return value(); }
};


// service_traits::MD5Sum< ::icra_roboin_msgs::XYOffsetRequest> should match 
// service_traits::MD5Sum< ::icra_roboin_msgs::XYOffset > 
template<>
struct MD5Sum< ::icra_roboin_msgs::XYOffsetRequest>
{
  static const char* value()
  {
    return MD5Sum< ::icra_roboin_msgs::XYOffset >::value();
  }
  static const char* value(const ::icra_roboin_msgs::XYOffsetRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::icra_roboin_msgs::XYOffsetRequest> should match 
// service_traits::DataType< ::icra_roboin_msgs::XYOffset > 
template<>
struct DataType< ::icra_roboin_msgs::XYOffsetRequest>
{
  static const char* value()
  {
    return DataType< ::icra_roboin_msgs::XYOffset >::value();
  }
  static const char* value(const ::icra_roboin_msgs::XYOffsetRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::icra_roboin_msgs::XYOffsetResponse> should match 
// service_traits::MD5Sum< ::icra_roboin_msgs::XYOffset > 
template<>
struct MD5Sum< ::icra_roboin_msgs::XYOffsetResponse>
{
  static const char* value()
  {
    return MD5Sum< ::icra_roboin_msgs::XYOffset >::value();
  }
  static const char* value(const ::icra_roboin_msgs::XYOffsetResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::icra_roboin_msgs::XYOffsetResponse> should match 
// service_traits::DataType< ::icra_roboin_msgs::XYOffset > 
template<>
struct DataType< ::icra_roboin_msgs::XYOffsetResponse>
{
  static const char* value()
  {
    return DataType< ::icra_roboin_msgs::XYOffset >::value();
  }
  static const char* value(const ::icra_roboin_msgs::XYOffsetResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ICRA_ROBOIN_MSGS_MESSAGE_XYOFFSET_H
