// Generated by gencpp from file icra_roboin_msgs/YawGain.msg
// DO NOT EDIT!


#ifndef ICRA_ROBOIN_MSGS_MESSAGE_YAWGAIN_H
#define ICRA_ROBOIN_MSGS_MESSAGE_YAWGAIN_H

#include <ros/service_traits.h>


#include <icra_roboin_msgs/YawGainRequest.h>
#include <icra_roboin_msgs/YawGainResponse.h>


namespace icra_roboin_msgs
{

struct YawGain
{

typedef YawGainRequest Request;
typedef YawGainResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct YawGain
} // namespace icra_roboin_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::icra_roboin_msgs::YawGain > {
  static const char* value()
  {
    return "223542de9427e9df0f0b5bfbdc1715cb";
  }

  static const char* value(const ::icra_roboin_msgs::YawGain&) { return value(); }
};

template<>
struct DataType< ::icra_roboin_msgs::YawGain > {
  static const char* value()
  {
    return "icra_roboin_msgs/YawGain";
  }

  static const char* value(const ::icra_roboin_msgs::YawGain&) { return value(); }
};


// service_traits::MD5Sum< ::icra_roboin_msgs::YawGainRequest> should match 
// service_traits::MD5Sum< ::icra_roboin_msgs::YawGain > 
template<>
struct MD5Sum< ::icra_roboin_msgs::YawGainRequest>
{
  static const char* value()
  {
    return MD5Sum< ::icra_roboin_msgs::YawGain >::value();
  }
  static const char* value(const ::icra_roboin_msgs::YawGainRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::icra_roboin_msgs::YawGainRequest> should match 
// service_traits::DataType< ::icra_roboin_msgs::YawGain > 
template<>
struct DataType< ::icra_roboin_msgs::YawGainRequest>
{
  static const char* value()
  {
    return DataType< ::icra_roboin_msgs::YawGain >::value();
  }
  static const char* value(const ::icra_roboin_msgs::YawGainRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::icra_roboin_msgs::YawGainResponse> should match 
// service_traits::MD5Sum< ::icra_roboin_msgs::YawGain > 
template<>
struct MD5Sum< ::icra_roboin_msgs::YawGainResponse>
{
  static const char* value()
  {
    return MD5Sum< ::icra_roboin_msgs::YawGain >::value();
  }
  static const char* value(const ::icra_roboin_msgs::YawGainResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::icra_roboin_msgs::YawGainResponse> should match 
// service_traits::DataType< ::icra_roboin_msgs::YawGain > 
template<>
struct DataType< ::icra_roboin_msgs::YawGainResponse>
{
  static const char* value()
  {
    return DataType< ::icra_roboin_msgs::YawGain >::value();
  }
  static const char* value(const ::icra_roboin_msgs::YawGainResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ICRA_ROBOIN_MSGS_MESSAGE_YAWGAIN_H
