(cl:in-package icra_roboin_msgs-srv)
(cl:export '(STAMP-VAL
          STAMP
          REQUEST_SENDER-VAL
          REQUEST_SENDER
          CONFIRM-VAL
          CONFIRM
          STAMP-VAL
          STAMP
          MY_ID-VAL
          MY_ID
          MY_LIFE-VAL
          MY_LIFE
          MY_TEAMTYPE-VAL
          MY_TEAMTYPE
          ROBOT_DAMAGE_TYPE-VAL
          ROBOT_DAMAGE_TYPE
          ROBOT_DAMAGE_ARMOR-VAL
          ROBOT_DAMAGE_ARMOR
          MY_BONUS_ZONE-VAL
          MY_BONUS_ZONE
          MY_HP-VAL
          MY_HP
          ALLY_LIFE-VAL
          ALLY_LIFE
          ENEMY1_LIFE-VAL
          ENEMY1_LIFE
          ENEMY2_LIFE-VAL
          ENEMY2_LIFE
          ENEMY_BONUS_ZONE-VAL
          ENEMY_BONUS_ZONE
          TIME_PASSED_FROM_START-VAL
          TIME_PASSED_FROM_START
          LAST_BUFF_TIME-VAL
          LAST_BUFF_TIME
          LAST_SUPPLY_TIME-VAL
          LAST_SUPPLY_TIME
          ENEMY_LAST_BUFF_TIME-VAL
          ENEMY_LAST_BUFF_TIME
          AMMO-VAL
          AMMO
          GAME_STATUS-VAL
          GAME_STATUS
          ROBOT_BONUS-VAL
          ROBOT_BONUS
          SUPPLIER_STATUS-VAL
          SUPPLIER_STATUS
          GAME_RESULT-VAL
          GAME_RESULT
          MY_POSE-VAL
          MY_POSE
          ENEMY_POSE1-VAL
          ENEMY_POSE1
          ENEMY_POSE2-VAL
          ENEMY_POSE2
          HOW_MANY_ENEMIES_DETECTED-VAL
          HOW_MANY_ENEMIES_DETECTED
          IS_ENEMY_1_DETECTED-VAL
          IS_ENEMY_1_DETECTED
          IS_ENEMY_2_DETECTED-VAL
          IS_ENEMY_2_DETECTED
))