(cl:defpackage icra_roboin_msgs-srv
  (:use )
  (:export
   "BLACKBOARDGENERALINFO"
   "<BLACKBOARDGENERALINFO-REQUEST>"
   "BLACKBOARDGENERALINFO-REQUEST"
   "<BLACKBOARDGENERALINFO-RESPONSE>"
   "BLACKBOARDGENERALINFO-RESPONSE"
   "PITCHGAIN"
   "<PITCHGAIN-REQUEST>"
   "PITCHGAIN-REQUEST"
   "<PITCHGAIN-RESPONSE>"
   "PITCHGAIN-RESPONSE"
   "XYOFFSET"
   "<XYOFFSET-REQUEST>"
   "XYOFFSET-REQUEST"
   "<XYOFFSET-RESPONSE>"
   "XYOFFSET-RESPONSE"
   "YAWGAIN"
   "<YAWGAIN-REQUEST>"
   "YAWGAIN-REQUEST"
   "<YAWGAIN-RESPONSE>"
   "YAWGAIN-RESPONSE"
  ))

