# head_controller:
#   type: "effort_controllers/JointTrajectoryController"
#   joints:
#     - base_link_to_yaw_joint
#     - base_link_to_pitch_joint

#   constraints:
#     goal_time: 0.5                   # Override default
#     stopped_velocity_tolerance: 0.02 # Override default
#     base_link_to_yaw_joint:
#       trajectory: 0.05               # Not enforced if unspecified
#       goal: 0.02                     # Not enforced if unspecified
#     base_link_to_pitch_joint:
#       goal: 0.01                     # Not enforced if unspecified

#   gains: # Required because we're controlling an effort interface
#     base_link_to_yaw_joint: {p: 100,  d: 1, i: 1, i_clamp: 1}
#     base_link_to_pitch_joint: {p: 100,  d: 1, i: 1, i_clamp: 1}

#   state_publish_rate:  25            # Override default
#   action_monitor_rate: 30            # Override default
#   stop_trajectory_duration: 0        # Override default

robomaster_ai:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  

  # Velocity Controllers ---------------------------------------
  yaw_velocity_controller:
    type: effort_controllers/JointVelocityController
    joint: base_link_to_yaw_joint
    pid: {p: 10.0, i: 0.1, d: 1.0}

  pitch_velocity_controller:
    type: effort_controllers/JointVelocityController
    joint: base_link_to_pitch_joint
    pid: {p: 10.0, i: 0.1, d: 1.0}