(cl:defpackage icra_roboin_msgs-msg
  (:use )
  (:export
   "<CIRCLEOBSTACLE>"
   "CIRCLEOBSTACLE"
   "<OBSTACLES>"
   "OBSTACLES"
   "<SEGMENTOBSTACLE>"
   "SEGMENTOBSTACLE"
   "<YOLODETECTIONACTION>"
   "YOLODETECTIONACTION"
   "<YOLODETECTIONACTIONFEEDBACK>"
   "YOLODETECTIONACTIONFEEDBACK"
   "<YOLODETECTIONACTIONGOAL>"
   "YOLODETECTIONACTIONGOAL"
   "<YOLODETECTIONACTIONRESULT>"
   "YOLODETECTIONACTIONRESULT"
   "<YOLODETECTIONFEEDBACK>"
   "YOLODETECTIONFEEDBACK"
   "<YOLODETECTIONGOAL>"
   "YOLODETECTIONGOAL"
   "<YOLODETECTIONINFO>"
   "YOLODETECTIONINFO"
   "<YOLODETECTIONRESULT>"
   "YOLODETECTIONRESULT"
  ))

