; Auto-generated. Do not edit!


(cl:in-package icra_roboin_msgs-msg)


;//! \htmlinclude YoloDetectionGoal.msg.html

(cl:defclass <YoloDetectionGoal> (roslisp-msg-protocol:ros-message)
  ((command
    :reader command
    :initarg :command
    :type cl:fixnum
    :initform 0))
)

(cl:defclass YoloDetectionGoal (<YoloDetectionGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <YoloDetectionGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'YoloDetectionGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name icra_roboin_msgs-msg:<YoloDetectionGoal> is deprecated: use icra_roboin_msgs-msg:YoloDetectionGoal instead.")))

(cl:ensure-generic-function 'command-val :lambda-list '(m))
(cl:defmethod command-val ((m <YoloDetectionGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader icra_roboin_msgs-msg:command-val is deprecated.  Use icra_roboin_msgs-msg:command instead.")
  (command m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <YoloDetectionGoal>) ostream)
  "Serializes a message object of type '<YoloDetectionGoal>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'command)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <YoloDetectionGoal>) istream)
  "Deserializes a message object of type '<YoloDetectionGoal>"
    (cl:setf (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'command)) (cl:read-byte istream))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<YoloDetectionGoal>)))
  "Returns string type for a message object of type '<YoloDetectionGoal>"
  "icra_roboin_msgs/YoloDetectionGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'YoloDetectionGoal)))
  "Returns string type for a message object of type 'YoloDetectionGoal"
  "icra_roboin_msgs/YoloDetectionGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<YoloDetectionGoal>)))
  "Returns md5sum for a message object of type '<YoloDetectionGoal>"
  "36e1d21d1340e2a5e93f075b6457cbdf")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'YoloDetectionGoal)))
  "Returns md5sum for a message object of type 'YoloDetectionGoal"
  "36e1d21d1340e2a5e93f075b6457cbdf")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<YoloDetectionGoal>)))
  "Returns full string definition for message of type '<YoloDetectionGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#Send a flag to server to control the thread start, pause, restart and stop~%#command == 1 start~%#command == 2 pause~%#command == 3 stop~%uint8 command~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'YoloDetectionGoal)))
  "Returns full string definition for message of type 'YoloDetectionGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#Send a flag to server to control the thread start, pause, restart and stop~%#command == 1 start~%#command == 2 pause~%#command == 3 stop~%uint8 command~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <YoloDetectionGoal>))
  (cl:+ 0
     1
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <YoloDetectionGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'YoloDetectionGoal
    (cl:cons ':command (command msg))
))
