; Auto-generated. Do not edit!


(cl:in-package icra_roboin_msgs-msg)


;//! \htmlinclude YoloDetectionResult.msg.html

(cl:defclass <YoloDetectionResult> (roslisp-msg-protocol:ros-message)
  ((result
    :reader result
    :initarg :result
    :type cl:float
    :initform 0.0))
)

(cl:defclass YoloDetectionResult (<YoloDetectionResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <YoloDetectionResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'YoloDetectionResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name icra_roboin_msgs-msg:<YoloDetectionResult> is deprecated: use icra_roboin_msgs-msg:YoloDetectionResult instead.")))

(cl:ensure-generic-function 'result-val :lambda-list '(m))
(cl:defmethod result-val ((m <YoloDetectionResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader icra_roboin_msgs-msg:result-val is deprecated.  Use icra_roboin_msgs-msg:result instead.")
  (result m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <YoloDetectionResult>) ostream)
  "Serializes a message object of type '<YoloDetectionResult>"
  (cl:let ((bits (roslisp-utils:encode-single-float-bits (cl:slot-value msg 'result))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <YoloDetectionResult>) istream)
  "Deserializes a message object of type '<YoloDetectionResult>"
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'result) (roslisp-utils:decode-single-float-bits bits)))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<YoloDetectionResult>)))
  "Returns string type for a message object of type '<YoloDetectionResult>"
  "icra_roboin_msgs/YoloDetectionResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'YoloDetectionResult)))
  "Returns string type for a message object of type 'YoloDetectionResult"
  "icra_roboin_msgs/YoloDetectionResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<YoloDetectionResult>)))
  "Returns md5sum for a message object of type '<YoloDetectionResult>"
  "db954e5de3aba73b237d07575e5cac28")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'YoloDetectionResult)))
  "Returns md5sum for a message object of type 'YoloDetectionResult"
  "db954e5de3aba73b237d07575e5cac28")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<YoloDetectionResult>)))
  "Returns full string definition for message of type '<YoloDetectionResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%float32 result~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'YoloDetectionResult)))
  "Returns full string definition for message of type 'YoloDetectionResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%float32 result~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <YoloDetectionResult>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <YoloDetectionResult>))
  "Converts a ROS message object to a list"
  (cl:list 'YoloDetectionResult
    (cl:cons ':result (result msg))
))
